#Default port is 8761
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 1
  serviceUrl:
    defaultZone: http://192.168.43.80:8761
  
